const fetch = require('isomorphic-fetch');
const cheerio = require('cheerio');
const JSDOM = require('jsdom').JSDOM;


const artists1 = [
    "/listamadur/31-februar",
    "/listamadur/abe-most",
    "/listamadur/addi-800",
    "/listamadur/agla-marta-sigurjonsdottir",
    "/listamadur/alan-murphy",
    "/listamadur/alan-spenner",
    "/listamadur/alex-somers",
    "/listamadur/alma-gudmundsdottir",
    "/listamadur/amiina",
    "/listamadur/andrea-gylfadottir",
    "/listamadur/andrew-lloyd-webber",
    "/listamadur/andrew-nichollis",
    "/listamadur/andres-gunnlaugsson",
    "/listamadur/andres-indridason",
    "/listamadur/andri-geir-arnason",
    "/listamadur/andrzej-kleina",
    "/listamadur/anna-bjork-birgisdottir",
    "/listamadur/anna-gudny-gudmundsdottir",
    "/listamadur/anna-maguire",
    "/listamadur/anna-sigurbjornsdottir",
    "/listamadur/arna-kristin-einarsdottir",
    "/listamadur/arnbjorg-hlif-valsdottir",
    "/listamadur/arngrimur-fannar-haraldsson",
    "/listamadur/atli-orvarsson",
    "/listamadur/audur-agla-oladottir",
    "/listamadur/audur-gudjonsdottir",
    "/listamadur/audur-ingvadottir",
    "/listamadur/axel-arnason",
    "/listamadur/agust-aevar-gunnarsson",
    "/listamadur/agusta-jonsdottir",
    "/listamadur/agusta-maria-jonsdottir",
    "/listamadur/agusta-osk-oskarsdottir",
    "/listamadur/arni-askelsson",
    "/listamadur/arni-gustafsson",
    "/listamadur/arni-sigurdsson",
    "/listamadur/asdis-arnardottir",
    "/listamadur/asgeir-jon-asgeirsson",
    "/listamadur/asgeir-jonsson",
    "/listamadur/asgeir-oskarsson",
    "/listamadur/asgeir-steingrimsson",
    "/listamadur/asta-olafsdottir",
    "/listamadur/astvaldur-traustason",
    "/listamadur/baldvin-b-aalen",
    "/listamadur/barnakor-karsnesskola",
    "/listamadur/benedikt-brynleifsson",
    "/listamadur/benedikt-elfar",
    "/listamadur/bergrun-snaebjornsdottir",
    "/listamadur/bergsveinn-areliusson",
    "/listamadur/bergur-geirsson",
    "/listamadur/bergur-mar-bernburg",
    "/listamadur/bergur-thor-ingolfsson",
    "/listamadur/bernhardur-wilkinsson",
    "/listamadur/bernie-holland",
    "/listamadur/bill-champlain",
    "/listamadur/birgir-baldursson",
    "/listamadur/birgir-bragason",
    "/listamadur/birgir-johann-birgisson",
    "/listamadur/birgir-jon-birgisson",
    "/listamadur/birgir-jonsson",
    "/listamadur/birgir-nielsen",
    "/listamadur/birna-hafstein",
    "/listamadur/bitlavinafelagid",
    "/listamadur/bjarni-bragi-kjartansson",
    "/listamadur/bjarni-gudmundsson",
    "/listamadur/bjarni-sigurdarson",
    "/listamadur/bjorgvin-gislason",
    "/listamadur/bjorgvin-halldorsson",
    "/listamadur/bjorgvin-ploder",
    "/listamadur/bjorn-jorundur-fridbjornsson",
    "/listamadur/bjorn-stefansson",
    "/listamadur/bjorn-tomas-kjaran",
    "/listamadur/bjorn-thor-sigbjornsson",
    "/listamadur/bob-merritt",
    "/listamadur/bob-saget",
    "/listamadur/borgar-magnason",
    "/listamadur/botnledja",
    "/listamadur/brjann-ingason",
    "/listamadur/bryan-allen-smith-iii",
    "/listamadur/bryndis-bjorgvinsdottir",
    "/listamadur/bryndis-palsdottir",
    "/listamadur/brynhildur-bjornsdottir",
    "/listamadur/bubbi-morthens",
    "/listamadur/buff",
    "/listamadur/carlos-bongo",
    "/listamadur/carlos-rios",
    "/listamadur/carmen-twillie",
    "/listamadur/centaur",
    "/listamadur/chris-kasych",
    "/listamadur/christian-diethard",
    "/listamadur/christian-falk",
    "/listamadur/curver",
    "/listamadur/dadi-dax",
    "/listamadur/dadi-kolbeinsson",
    "/listamadur/dan-cassidy",
    "/listamadur/daniel-agust-haraldsson",
    "/listamadur/daniel-bjarnason",
    "/listamadur/daniel-hordur-skulason",
    "/listamadur/danny-pollock",
    "/listamadur/daryl-runswick",
    "/listamadur/dave-hutchins",
    "/listamadur/david-bobroff",
    "/listamadur/david-logeman",
    "/listamadur/david-nooteboom",
    "/listamadur/dean-ferrel",
    "/listamadur/dimma",
    "/listamadur/dora-bjorgvinsdottir",
    "/listamadur/dralon-korinn",
    "/listamadur/e-chiprot",
    "/listamadur/eamonn-dougan",
    "/listamadur/edda-run-olafsdottir",
    "/listamadur/edward-frederiksen",
    "/listamadur/edvard-larusson",
    "/listamadur/eggert-palsson",
    "/listamadur/egill-bjarnason",
    "/listamadur/egill-lar",
    "/listamadur/egill-olafsson",
    "/listamadur/eidur-alfredsson",
    "/listamadur/eidur-arnarson",
    "/listamadur/einar-bardarson",
    "/listamadur/einar-bragi-bragason",
    "/listamadur/einar-johannesson",
    "/listamadur/einar-jonsson",
    "/listamadur/einar-runarsson",
    "/listamadur/einar-scheving",
    "/listamadur/einar-sigurdsson",
    "/listamadur/einar-thor-johannsson",
    "/listamadur/einar-orn-benediktsson",
    "/listamadur/eirikur-hauksson",
    "/listamadur/eirikur-orri-olafsson",
    "/listamadur/eirikur-sigurdsson",
    "/listamadur/eirikur-orn-palsson",
    "/listamadur/elizabeth-carlsson",
    "/listamadur/elinborg-ingunn-olafsdottir",
    "/listamadur/elisa-maria-geirsdottir",
    "/listamadur/ellert-b-thorvaldsson",
    "/listamadur/emelia-baldursdottir",
    "/listamadur/emil-fridfinnsson",
    "/listamadur/emiliana-torrini",
    "/listamadur/enskt-thjodlag",
    "/listamadur/eric-isip",
    "/listamadur/erik-zobler",
    "/listamadur/erikur-orri-olafsson",
    "/listamadur/erla-fridgeirsdottir",
    "/listamadur/erla-karadottir",
    "/listamadur/erna-thorarinsdottir",
    "/listamadur/ernie-watts",
    "/listamadur/eva-asrun-albertsdottir",
    "/listamadur/eydis-sylvia-einarsdottir",
    "/listamadur/eyjolfur-bjarni-alfredsson",
    "/listamadur/eyjolfur-johannsson",
    "/listamadur/eyjolfur-kristjansson",
    "/listamadur/eysteinn-eysteinsson",
    "/listamadur/eythor-gunnarsson",
    "/listamadur/fannar-viggoson",
    "/listamadur/fanny-k-tryggvadottir",
    "/listamadur/finnur-johannsson",
    "/listamadur/flood",
    "/listamadur/frank-aarnink",
    "/listamadur/fridrik-juliusson-g",
    "/listamadur/fridrik-karlsson",
    "/listamadur/fridrik-sturluson",
    "/listamadur/fridthjofur-i-sigurdsson",
    "/listamadur/frosti-logason",
    "/listamadur/gary-herbig",
    "/listamadur/galan",
    "/listamadur/georg-haraldsson",
    "/listamadur/georg-holm",
    "/listamadur/george-frideric-handel",
    "/listamadur/gisli-magnason",
    "/listamadur/gisli-mar-sigurjonsson",
    "/listamadur/gospelkor-reykjavikur",
    "/listamadur/greifarnir",
    "/listamadur/greifarnir-0",
    "/listamadur/greta-gudnadottir",
    "/listamadur/greta-rognvaldsdottir",
    "/listamadur/greta-salome-stefansdottir",
    "/listamadur/gretar-orvarsson",
    "/listamadur/groa-margret-valdimarsdottir",
    "/listamadur/gudlaug-drofn-olafsdottir",
    "/listamadur/gudlaugur-kristinn-ottarsson",
    "/listamadur/gudmundur-bjarni-sigurdsson",
    "/listamadur/gudmundur-hafsteinsson",
    "/listamadur/gudmundur-jonsson",
    "/listamadur/gudmundur-kristinn-jonsson",
    "/listamadur/gudmundur-kristmundsson",
    "/listamadur/gudmundur-petursson",
    "/listamadur/gudni",
    "/listamadur/gudny-jonasdottir",
    "/listamadur/gudridur-palsdottir",
    "/listamadur/gudridur-sigurdardottir",
    "/listamadur/gudrun-gunnarsdottir",
    "/listamadur/gudrun-haflidadottir",
    "/listamadur/gudrun-ola-jonsdottir",
    "/listamadur/gudrun-th-sigurdardottir",
    "/listamadur/gudrun-thorarinsdottir",
    "/listamadur/gunnar-arnason",
    "/listamadur/gunnar-olason",
    "/listamadur/gunnar-smari-helgason",
    "/listamadur/gunnar-thor-jonsson",
    "/listamadur/gunnar-thordarson",
    "/listamadur/gunnhildur-dadadottir",
    "/listamadur/gunnlaugur-briem",
    "/listamadur/gunnlaugur-torfi-stefansson",
    "/listamadur/gylfi-kristinsson",
    "/listamadur/haffi-tempo",
    "/listamadur/hafsteinn-gudmundsson",
    "/listamadur/hafthor-gudmundsson",
    "/listamadur/halldor-gunnlaugur-hauksson",
    "/listamadur/halldor-johannesson",
    "/listamadur/halldor-kristinsson",
    "/listamadur/hallfridur-olafsdottir",
    "/listamadur/hallur-ingolfsson",
    "/listamadur/hanna-dora-sturludottir",
    "/listamadur/hannes-heimir-fridbjarnarson",
    "/listamadur/hannes-orn-blandon",
    "/listamadur/hans-jensson",
    "/listamadur/hara-systur",
    "/listamadur/haraldur-vignir-sveinbjornsson",
    "/listamadur/haraldur-thorsteinsson",
    "/listamadur/havardur-tryggvason",
    "/listamadur/heidrun-kjartansdottir",
    "/listamadur/helena-maria-jonsdottir",
    "/listamadur/helga-bjorg-agustsdottir",
    "/listamadur/helga-bolladottir",
    "/listamadur/helga-moller",
    "/listamadur/helga-steinunn-torfadottir",
    "/listamadur/helga-thorarinsdottir",
    "/listamadur/helgi-bjornsson",
    "/listamadur/helgi-gudmundsson",
    "/listamadur/helgi-hrafn-jonsson",
    "/listamadur/henry-lewy",
    "/listamadur/herbert-vidarsson",
    "/listamadur/herdis-anna-jonsdottir",
    "/listamadur/hermann-karlsson",
    "/listamadur/herramenn",
    "/listamadur/herramenn-0",
    "/listamadur/hildur-arsaelsdottir",
    "/listamadur/hildur-jonsdottir",
    "/listamadur/hildur-magnusdottir",
    "/listamadur/hinrik-vilhjalmsson",
    "/listamadur/hjordis-geirsdottir",
    "/listamadur/hjordis-sigurdardottir",
    "/listamadur/hjorleifur-orn-jonsson",
    "/listamadur/hjortur-gudbjartsson",
    "/listamadur/hjortur-gunnlaugsson",
    "/listamadur/hjortur-howser",
    "/listamadur/hlin-erlendsdottir",
    "/listamadur/howard-mcdonald",
    "/listamadur/holmfridur-thoroddsdottir",
    "/listamadur/hrafn-asgeirsson",
    "/listamadur/hrafnkell-orri-egilsson",
    "/listamadur/hrafnkell-palmason",
    "/listamadur/hrannar-ingimarsson",
    "/listamadur/hrannar-petursson",
    "/listamadur/hrefna-hallgrimsdottir",
    "/listamadur/hrobjartur-robertsson",
    "/listamadur/hrolfur-saemundsson",
    "/listamadur/hronn-svansdottir",
    "/listamadur/hofundur-othekktur",
    "/listamadur/hoskuldur-o-larusson",
    "/listamadur/ian-huffam",
    "/listamadur/inga-ros-ingolfsdottir",
    "/listamadur/ingi-gardar-erlendsson",
    "/listamadur/ingi-snaer-skulason",
    "/listamadur/ingibjorg-einarsdottir",
    "/listamadur/ingo-geirdal",
    "/listamadur/ingolfur-gudjonsson",
    "/listamadur/ingolfur-magnusson",
    "/listamadur/ingolfur-sigurdsson",
    "/listamadur/ingrid-karlsdottir",
    "/listamadur/ingvar-jonsson",
    "/listamadur/iris-erlingsdottir",
    "/listamadur/iris-kristinsdottir",
    "/listamadur/iris-lind-verudottir",
    "/listamadur/islenskt-thjodlag",
    "/listamadur/ivar-bongo",
    "/listamadur/ivar-snorrason",
    "/listamadur/jakob-frimann-magnusson",
    "/listamadur/jakob-smari-magnusson",
    "/listamadur/jakob-tryggvason",
    "/listamadur/jason-gossman",
    "/listamadur/jeff-baxter",
    "/listamadur/jens-hansson",
    "/listamadur/jeremy-lubbock",
    "/listamadur/jerry-hey",
    "/listamadur/jette-svava-jakobsdottir",
    "/listamadur/joe-barresi",
    "/listamadur/john-giblin",
    "/listamadur/john-jones",
    "/listamadur/john-lennon",
    "/listamadur/john-susswell",
    "/listamadur/jojo",
    "/listamadur/joop-stokkermans",
    "/listamadur/joseph-ognibene",
    "/listamadur/jo-jo",
    "/listamadur/joel-palsson",
    "/listamadur/johann-asmundsson",
    "/listamadur/johann-bachmann",
    "/listamadur/johann-g-johannsson",
    "/listamadur/johann-helgason",
    "/listamadur/johann-hjorleifsson",
    "/listamadur/johann-sigurdarson",
    "/listamadur/johann-stefansson",
    "/listamadur/johanna-baldursdottir",
    "/listamadur/johanna-v-thorhallsdottir",
    "/listamadur/johannes-eidsson",
    "/listamadur/johannes-georgsson",
    "/listamadur/jon-bjorgvin-stefansson",
    "/listamadur/jon-elvar-hafsteinsson",
    "/listamadur/jon-halldor-finnsson",
    "/listamadur/jon-helgason",
    "/listamadur/jon-ingi-thorvaldsson",
    "/listamadur/jon-kjell-seljeseth",
    "/listamadur/jon-olafsson",
    "/listamadur/jon-omar-erlingsson",
    "/listamadur/jon-skuggi",
    "/listamadur/jon-thor-birgisson",
    "/listamadur/jonas-fridrik",
    "/listamadur/jonina-audur-hilmarsdottir",
    "/listamadur/julia-mogensen",
    "/listamadur/juliana-elin-kjartansdottir",
    "/listamadur/julius-freyr-gudmundsson",
    "/listamadur/karl-ottar-geirsson",
    "/listamadur/karl-sighvatsson",
    "/listamadur/karl-th-thorvaldsson",
    "/listamadur/karl-orvarsson",
    "/listamadur/karmen-lowe",
    "/listamadur/kathryn-harrisson",
    "/listamadur/katie-jane-garside",
    "/listamadur/ken-thomas",
    "/listamadur/kevin-metcalfe",
    "/listamadur/kippi-kaninus",
    "/listamadur/kjartan-freyr-villhjalmsson",
    "/listamadur/kjartan-gudnason",
    "/listamadur/kjartan-hakonarson",
    "/listamadur/kjartan-oskarsson",
    "/listamadur/kjartan-sveinsson",
    "/listamadur/kjartan-valdimarsson",
    "/listamadur/klara-osk-eliasdottir",
    "/listamadur/klemens-arnarsson",
    "/listamadur/kristbjorg-k-solmundardottir",
    "/listamadur/kristinn-s-sturluson",
    "/listamadur/kristin-bjorg-ragnarsdottir",
    "/listamadur/kristin-larusdottir",
    "/listamadur/kristin-osk-gestsdottir",
    "/listamadur/kristin-ran-juliusdottir",
    "/listamadur/kristjana-stefansdottir",
    "/listamadur/kristjan-blondal",
    "/listamadur/kristjan-edelstein",
    "/listamadur/kristjan-frimann",
    "/listamadur/kristjan-gudmundsson",
    "/listamadur/kristjan-matthiasson",
    "/listamadur/kristjan-th-stephensen",
    "/listamadur/krummi-bjorgvinsson",
    "/listamadur/kumen",
    "/listamadur/laufey-sigurdardottir",
    "/listamadur/laura-sisk",
    "/listamadur/leifur-jonsson",
    "/listamadur/lilja-valdimarsdottir",
    "/listamadur/lin-wei",
    "/listamadur/lina-sveinbjarnardottir",
    "/listamadur/louisa-mullenger",
    "/listamadur/lovisa-b-fjeldsted",
    "/listamadur/ludvig-kari-forberg",
    "/listamadur/magnus-einarsson",
    "/listamadur/magnus-eiriksson",
    "/listamadur/magnus-sigmundsson",
    "/listamadur/magnus-stefansson",
    "/listamadur/magnus-tryggvason-eliassen",
    "/listamadur/magnus-thor-sigmundsson",
    "/listamadur/magnus-oder",
    "/listamadur/mandy-parnell",
    "/listamadur/manolo-badrena",
    "/listamadur/marco-migilari",
    "/listamadur/margret-arnadottir",
    "/listamadur/margret-b-kjartansdottir",
    "/listamadur/margret-kristjansdottir",
    "/listamadur/margret-sigurdardottir",
    "/listamadur/margret-thorsteinsdottir",
    "/listamadur/maria-huld-markan-sigfusdottir",
    "/listamadur/maria-magnusdottir",
    "/listamadur/maria-weiss",
    "/listamadur/mark-dodson",
    "/listamadur/martial-nardeau",
    "/listamadur/matthias-hemstock",
    "/listamadur/matthias-matthiasson",
    "/listamadur/matthias-stefansson",
    "/listamadur/matthias-v-baldursson",
    "/listamadur/mani-svavarsson",
    "/listamadur/megas",
    "/listamadur/megas-nydonsk",
    "/listamadur/michal-urbaniak",
    "/listamadur/mike-bolivar",
    "/listamadur/mike-pollock",
    "/listamadur/minus",
    "/listamadur/modfisk",
    "/listamadur/monika-abendroth",
    "/listamadur/moeidur-sigurdardottir",
    "/listamadur/nanna-kristin-johannsdottir",
    "/listamadur/neil-hubbard",
    "/listamadur/nick-cathcart-jones",
    "/listamadur/nicole-vala-cariglia",
    "/listamadur/njall-thordarson",
    "/listamadur/nylon",
    "/listamadur/ny-donsk-sinfo",
    "/listamadur/nydonsk",
    "/listamadur/oddur-bjornsson",
    "/listamadur/oddur-steinn-einarsson",
    "/listamadur/monsters-and-men",
    "/listamadur/olga-bjork-olafsdottir",
    "/listamadur/orri-pall-dyrason",
    "/listamadur/olafur-e-runarsson",
    "/listamadur/olafur-gaukur-thorhallsson",
    "/listamadur/olafur-halldorsson",
    "/listamadur/olafur-holm-einarsson",
    "/listamadur/olafur-mar-svavarsson",
    "/listamadur/olafur-steindorsson",
    "/listamadur/olof-julia-kjartansdottir",
    "/listamadur/olof-s-oskarsdottir",
    "/listamadur/olof-thorvaldsdottir",
    "/listamadur/olof-thorvardsdottir",
    "/listamadur/omar-orn-hauksson",
    "/listamadur/oskar-einarsson",
    "/listamadur/oskar-pall-sveinsson",
    "/listamadur/paul-brown",
    "/listamadur/paul-mccartney",
    "/listamadur/palina-arnadottir",
    "/listamadur/pall-hannesson",
    "/listamadur/pall-oskar-hjalmtyrsson",
    "/listamadur/palmi-gunnarsson",
    "/listamadur/palmi-j-sigurhjartarson",
    "/listamadur/pelican",
    "/listamadur/percy-sledge",
    "/listamadur/peter-banks",
    "/listamadur/petur-gretarsson",
    "/listamadur/petur-kristjansson",
    "/listamadur/petur-orn-gudmundsson",
    "/listamadur/phil-collins",
    "/listamadur/philippe-garcia",
    "/listamadur/plahnetan",
    "/listamadur/possibillies",
    "/listamadur/preston-heyman",
    "/listamadur/raddsvikararnir",
    "/listamadur/rafn-jonsson",
    "/listamadur/ragnhildur-gisladottir",
    "/listamadur/rakel-magnusdottir",
    "/listamadur/ray-russell",
    "/listamadur/regina-osk-oskarsdottir",
    "/listamadur/reykjavik-session-quartet",
    "/listamadur/reynir-gudmundsson",
    "/listamadur/rich-costey",
    "/listamadur/richard-berry",
    "/listamadur/richard-elliot",
    "/listamadur/richard-korn",
    "/listamadur/richard-pierce",
    "/listamadur/richard-talkowsky",
    "/listamadur/rick-smith",
    "/listamadur/roland-hartwell",
    "/listamadur/roy-babbington",
    "/listamadur/robert-thorhallsson",
    "/listamadur/rosa-hrund-gudmundsdottir",
    "/listamadur/ruth-reginalds",
    "/listamadur/runar-erlingsson",
    "/listamadur/runar-gb",
    "/listamadur/runar-gislason",
    "/listamadur/runar-juliusson",
    "/listamadur/runar-oskarsson",
    "/listamadur/runar-vilbergsson",
    "/listamadur/s-husky-hoskulds",
    "/listamadur/samuel-jon-samuelsson",
    "/listamadur/sarah-buckley",
    "/listamadur/salin-hans-jons-mins",
    "/listamadur/salin-og-gospel",
    "/listamadur/salin-og-sinfo",
    "/listamadur/sean-bradley",
    "/listamadur/selma-bjornsdottir",
    "/listamadur/sesselja-halldorsdottir",
    "/listamadur/sesselja-kristjansdottir",
    "/listamadur/shiv-shankar",
    "/listamadur/sif-tulinius",
    "/listamadur/sigridur-baldvinsdottir",
    "/listamadur/sigridur-beinteinsdottir",
    "/listamadur/sigrun-edvaldsdottir",
    "/listamadur/sigrun-hjalmtyrsdottir",
    "/listamadur/sigrun-jonsdottir",
    "/listamadur/sigtryggur-dyravordur",
    "/listamadur/sigur-ros",
    "/listamadur/sigurbjorn-bernhardsson",
    "/listamadur/sigurdur-bjarki-gunnarsson",
    "/listamadur/sigurdur-bjarni-gislason",
    "/listamadur/sigurdur-bjola-gardarsson",
    "/listamadur/sigurdur-fannar",
    "/listamadur/sigurdur-flosason",
    "/listamadur/sigurdur-geirdal",
    "/listamadur/sigurdur-grondal",
    "/listamadur/sigurdur-i-snorrason",
    "/listamadur/sigurdur-oddsson",
    "/listamadur/sigurdur-sigurdsson",
    "/listamadur/sigurdur-thorbergsson",
    "/listamadur/sigurdur-orn-jonsson",
    "/listamadur/sigurgeir-agnarsson",
    "/listamadur/sigurgeir-sigmundsson",
    "/listamadur/sigurjon-brink",
    "/listamadur/sigurlaug-edvaldsdottir",
    "/listamadur/sigurvald-ivar-helgason",
    "/listamadur/silli-geirdal",
    "/listamadur/sinfoniuhljomsveit-islands",
    "/listamadur/skitamorall",
    "/listamadur/skuli-gautason",
    "/listamadur/sniglabandid",
    "/listamadur/snorri-heimisson",
    "/listamadur/snorri-sigurdarson",
    "/listamadur/snaebjorg-snaebjarnardottir",
    "/listamadur/snaebjorn-gauti-snaebjornsson",
    "/listamadur/soldogg",
    "/listamadur/solon-islandus",
    "/listamadur/solrun-sumarlidadottir",
    "/listamadur/spilverk-thjodanna",
    "/listamadur/spoon",
    "/listamadur/stebbi-og-eyfi",
    "/listamadur/steef-van-oosterhout",
    "/listamadur/stefania-olafsdottir",
    "/listamadur/stefan-birkisson",
    "/listamadur/stefan-hallur-stefansson",
    "/listamadur/stefan-henry-henrysson",
    "/listamadur/stefan-hilmarsson",
    "/listamadur/stefan-hjorleifsson",
    "/listamadur/stefan-jakobsson",
    "/listamadur/stefan-s-stefansson",
    "/listamadur/stefan-orn-arnarson",
    "/listamadur/stefan-orn-gunnlaugsson",
    "/listamadur/steinar-erlingsson",
    "/listamadur/steingrimur-gudmundsson",
    "/listamadur/steinunn-olina-thorsteinsdottir",
    "/listamadur/steinunn-thora-camilla-sigurdardottir",
    "/listamadur/steve-anderson",
    "/listamadur/steve-forman",
    "/listamadur/steve-humphreys",
    "/listamadur/stjornin",
    "/listamadur/studmenn",
    "/listamadur/sturlaugur-jon-bjornsson",
    "/listamadur/suellen",
    "/listamadur/svanhildur-jakobsdottir",
    "/listamadur/svanhvit-fridriksdottir",
    "/listamadur/sveinn-birgisson",
    "/listamadur/sveinn-kjartansson",
    "/listamadur/sveinn-omar-gretarsson",
    "/listamadur/sveinn-th-geirsson",
    "/listamadur/sverrir-stormsker",
    "/listamadur/szymon-kuran",
    "/listamadur/saevar-gardarsson",
    "/listamadur/ted-jansen",
    "/listamadur/sixteen",
    "/listamadur/tim-rice",
    "/listamadur/todmobile",
    "/listamadur/tom-brown",
    "/listamadur/tom-scott",
    "/listamadur/tommy-johnson",
    "/listamadur/tony-roberts",
    "/listamadur/tomas-johannesson",
    "/listamadur/tomas-m-tomasson",
    "/listamadur/trausti-haraldsson",
    "/listamadur/trevor-spencer",
    "/listamadur/trio-jons-leifssonar",
    "/listamadur/una-sveinbjarnardottir",
    "/listamadur/utangardsmenn",
    "/listamadur/ulfhildur-geirsdottir",
    "/listamadur/vala-gestsdottir",
    "/listamadur/valdimar-bragi-bragason",
    "/listamadur/valgeir-gudjonsson",
    "/listamadur/valgeir-sigurdsson",
    "/listamadur/veigar-margeirsson",
    "/listamadur/venette-gloud",
    "/listamadur/victor-feldman",
    "/listamadur/villhjalmur-godi-fridriksson",
    "/listamadur/walter-turbitt",
    "/listamadur/xiii",
    "/listamadur/ymsir",
    "/listamadur/yr-johannsdottir",
    "/listamadur/zbigniew-dubik",
    "/listamadur/zebra",
    "/listamadur/thjodlag",
    "/listamadur/thorgils-bjorgvinsson",
    "/listamadur/thorkell-joelsson",
    "/listamadur/thorlakur-ludviksson",
    "/listamadur/thorsteinn-gunnarsson",
    "/listamadur/thorsteinn-magnusson",
    "/listamadur/thorvaldur-bjarni-thorvaldsson",
    "/listamadur/thorvaldur-skaftason",
    "/listamadur/thor-breidfjord",
    "/listamadur/thora-gisladottir",
    "/listamadur/thora-katrin-gunnarsdottir",
    "/listamadur/thorarinn-gretarsson",
    "/listamadur/thorarinn-mar-baldursson",
    "/listamadur/thordis-stross",
    "/listamadur/thordur-arnason",
    "/listamadur/thordur-gudmundsson",
    "/listamadur/thorhallur-i-halldorsson",
    "/listamadur/thorir-johannesson",
    "/listamadur/thorir-johannsson",
    "/listamadur/thorir-ulfarsson",
    "/listamadur/thorunn-bjornsdottir",
    "/listamadur/thorunn-marinosdottir",
    "/listamadur/thorunn-osk-marinosdottir",
    "/listamadur/throstur-jonsson",
    "/listamadur/aegir-thorberg-jonsson",
    "/listamadur/ornolfur-kristjansson",
    "/listamadur/ossur-geirsson"
];

const convertArtist = (dom) => {

    const isGroup = dom.window.document.body.querySelector('.artist-display').innerHTML.includes('Hljómsveit');

    dom.window.document.querySelector('link[rel=canonical]')

    let members = [];
    let albums = Array.from(dom.window.document.body.querySelectorAll('.pane-ismus-display-all-albums-of-artist table a')).map(item => item.getAttribute('href'));

    //
    if(isGroup) {
        const memberTables = dom.window.document.body.querySelectorAll('.pane-ismus-display-artist-member table.table');
        const table = memberTables.length > 1 ? memberTables[memberTables.length - 1] : memberTables[0];
        members = Array.from(table.querySelectorAll('tbody tr')).map(row => {
            return {
                name: row.children[0].querySelector('a').innerHTML,
                path: row.children[0].querySelector('a').getAttribute('href'),
                from: row.children[1].innerHTML,
                to: row.children[2].innerHTML,
                instruments: row.children[3].textContent,
            }
        });
    }

    const idArray = dom.window.document.body.getAttribute('class').match(/(page-node-)([0-9]+)/)
    return {
        path: dom.window.document.querySelector('link[rel=canonical]').getAttribute('href'),
        name: dom.window.document.querySelector('h1.page-header').innerHTML,
        id: Number(idArray[2]),
        group: isGroup,
        members: members,
        albums: albums
    }
};

//FETCH ALL ARTISTS LINKS
//
fetch('https://islensktonlist.is/tonlistarmenn')
    .then(response => response.text())
    .then(text => {
    const $ = cheerio.load(text);
    return $('.views-summary-unformatted').map((index, element) => $(element).text()).toArray();
}).then(items => {
    return items.map(i => {
        const res = i.replace('\n', '').match(/([\wÁÍÓÚÝÞÆÖ]).*(\(([0-9]*)\))/);
        return {
            letter: encodeURIComponent(res[1]),
            size: Number(res[3]),
            pages: Math.ceil(Number(res[3]) / 36)
        }
    }).reduce((accumulator, value) => {
        const urls = Array.from({length: value.pages}).map((i, index) => `/tonlistarmenn/${value.letter}?page=${index}`);
        return [...accumulator, ...urls];
    }, []);
}).then(pages => {
    const pagesRequests = pages.map(url => {
        return fetch(`https://islensktonlist.is${url}`).then(response => response.text())
    });
    return Promise.all(pagesRequests);
}).then(markups => {
    return markups.map(text => {
        const $ = cheerio.load(text);
        return $('.table-striped tbody .views-field-title a').map((index, element) => $(element).attr('href')).toArray()
    });
}).then(urls => {
    return urls.reduce((accumulator, item) => [...accumulator, ...item], [])
}).then(urls => {
    return urls.map(url => {
        return fetch(`https://islensktonlist.is${url}`).then(response => response.text())
    });
}).then(texts => {
    return texts.map(text => convertArtist(new JSDOM(text)))
}).then(result => console.log(JSON.stringify(result, undefined, 4)));


// fetch('https://islensktonlist.is/listamadur/arngrimur-fannar-haraldsson')
fetch('https://islensktonlist.is/listamadur/skitamorall')
// fetch('https://islensktonlist.is/listamadur/salin-hans-jons-mins')
// fetch('https://islensktonlist.is/listamadur/amiina')
    .then(response => response.text())
    .then(text => new JSDOM(text))
    .then(convertArtist)
    .then(console.log)



const getArtist = (url) => {
    return fetch(`https://islensktonlist.is${url}`)
        .then(response => response.text())
        .then(text => new JSDOM(text))
        .then(convertArtist)
};

const requests = artists8.map(getArtist);
Promise.all(requests).then(result => console.log(JSON.stringify(result, undefined, 4))).catch(error => console.log(JSON.stringify(error.message, undefined, 4)));
